### ISSUE TITLE
Colony

### ISSUE THREAD

**Issue by markusgumbel** [informatik-mannheim/Moduro-CC3D#1]
Label cells such that they can form a colony. Required for PAS. Trace the colonies to a log file.

**Comment by AngeloTorelli** [comment]
@juliandebatin in [PythonScriptManual](http://www.compucell3d.org/BinDoc/cc3d_binaries/Manuals/PythonScriptingManual_v.3.7.4.pdf) from page 23 until page 29 are the most important chapters (13. and 14.) for this task.
