### ISSUE TITLE
Wrong aborted flag

### ISSUE THREAD

**Issue by AngeloTorelli** [informatik-mannheim/Moduro-CC3D#26]
The value of aborted is set to false for every simulation run. 
The possible values could be:

- true if the simulation did not run through which would mean NOT Completed (which would not add additional information)
or
- true if a sudden stop of the simulation recording is detected (such as if fitness value was high and all of a sudden it stopped without a decline)

**Comment by markusgumbel** [comment]
Related to Moduro-Toolbox.
