### ISSUE TITLE
Time and Voxel independency

### ISSUE THREAD

**Issue by AngeloTorelli** [informatik-mannheim/Moduro-CC3D#7]
Indipendency throughout the entire project. Missing files:
- [x] NutrientGrowthSteppable
- [ ] OptimumSearchSteppable
- [x] TransformationSteppable

**Comment by markusgumbel** [comment]
@Angelo: I will do some work on the Optimum steppable...

**Comment by markusgumbel** [comment]
Have a look at the classes Logger/*FitnessSteppables.py.
